const fakeResponse = {
    accounts: [{
            account_id: 'r3qp4zVLnmCJ6mBBALp5Ivbnmv98gjilPXG8R',
            balances: [Object],
            mask: '0000',
            name: 'Plaid Checking',
            official_name: 'Plaid Gold Standard 0% Interest Checking',
            subtype: 'checking',
            type: 'depository'
        },
        {
            account_id: '7BP6WZAJD9SyndMM6jaeuQ9bAQD5xWiglawDa',
            balances: [Object],
            mask: '1111',
            name: 'Plaid Saving',
            official_name: 'Plaid Silver Standard 0.1% Interest Saving',
            subtype: 'savings',
            type: 'depository'
        },
        {
            account_id: 'eo6d8AVqWmSpDa887gxXhwdnbwBNXmSLdXxAK',
            balances: [Object],
            mask: '2222',
            name: 'Plaid CD',
            official_name: 'Plaid Bronze Standard 0.2% Interest CD',
            subtype: 'cd',
            type: 'depository'
        },
        {
            account_id: 'QKzEaxoeD3Im6laaPM1kce9AleGEjVSpMnjbr',
            balances: [Object],
            mask: '3333',
            name: 'Plaid Credit Card',
            official_name: 'Plaid Diamond 12.5% APR Interest Credit Card',
            subtype: 'credit card',
            type: 'credit'
        },
        {
            account_id: 'ZNbvGQVxWmIGZPRRx75gfjRk5jMlgaCgRvxZ8',
            balances: [Object],
            mask: '4444',
            name: 'Plaid Money Market',
            official_name: 'Plaid Platinum Standard 1.85% Interest Money Market',
            subtype: 'money market',
            type: 'depository'
        },
        {
            account_id: 'MAlpBrM1DKIGXDbbglyKfWwZAW3bazC9l5ma9',
            balances: [Object],
            mask: '5555',
            name: 'Plaid IRA',
            official_name: null,
            subtype: 'ira',
            type: 'brokerage'
        },
        {
            account_id: '1GJbDNpeE9IWNk44jZKVioX73o4lrxt5KaD6p',
            balances: [Object],
            mask: '6666',
            name: 'Plaid 401k',
            official_name: null,
            subtype: '401k',
            type: 'brokerage'
        }
    ],
    item: {
        available_products: ['assets',
            'auth',
            'balance',
            'credit_details',
            'identity',
            'income'
        ],
        billed_products: ['transactions'],
        error: null,
        institution_id: 'ins_3',
        item_id: 'xPxAZ4VdnQIW7yddBK9gi1MxQzXdXjTnz5wjW',
        webhook: ''
    },
    request_id: 'wbx9nOcRSsJx4sL',
    total_transactions: 16,
    transactions: [{
            account_id: '7BP6WZAJD9SyndMM6jaeuQ9bAQD5xWiglawDa',
            account_owner: null,
            amount: 25,
            category: [Array],
            category_id: '16001000',
            date: '2019-03-22',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'CREDIT CARD 3333 PAYMENT *//',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: '3qPyDjgWA9Hbqj776Ml9C83xya4mX4FqrLWoE',
            transaction_type: 'special',
            unofficial_currency_code: null
        },
        {
            account_id: 'r3qp4zVLnmCJ6mBBALp5Ivbnmv98gjilPXG8R',
            account_owner: null,
            amount: 5.4,
            category: [Array],
            category_id: '22006001',
            date: '2019-03-22',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'Uber 063015 SF**POOL**',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'll7ezvVXnyTrV733kpLnuoljJd5ZW5cZw5M9l',
            transaction_type: 'special',
            unofficial_currency_code: null
        },
        {
            account_id: 'ZNbvGQVxWmIGZPRRx75gfjRk5jMlgaCgRvxZ8',
            account_owner: null,
            amount: 5850,
            category: [Array],
            category_id: '16000000',
            date: '2019-03-21',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'ACH Electronic CreditGUSTO PAY 123456',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'eo6d8AVqWmSpDa887gxXhwdn6o3zy3ILdXx6N',
            transaction_type: 'special',
            unofficial_currency_code: null
        },
        {
            account_id: 'eo6d8AVqWmSpDa887gxXhwdnbwBNXmSLdXxAK',
            account_owner: null,
            amount: 1000,
            category: [Array],
            category_id: '21007000',
            date: '2019-03-21',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'CD DEPOSIT .INITIAL.',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'dpgxAWVl6mUP9egg7QmMU39ApkM58MUZMqXgy',
            transaction_type: 'special',
            unofficial_currency_code: null
        },
        {
            account_id: 'QKzEaxoeD3Im6laaPM1kce9AleGEjVSpMnjbr',
            account_owner: null,
            amount: 78.5,
            category: [Array],
            category_id: '17018000',
            date: '2019-03-20',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'Touchstone Climbing',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'aMkzLgVEbmiDg4wwRMBkc9oGa35je5f7avXdJ',
            transaction_type: 'place',
            unofficial_currency_code: null
        },
        {
            account_id: 'r3qp4zVLnmCJ6mBBALp5Ivbnmv98gjilPXG8R',
            account_owner: null,
            amount: -500,
            category: [Array],
            category_id: '22001000',
            date: '2019-03-20',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'United Airlines',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'qBlLarVmy8Sp76MM3RLGhkeZ7Mza9zhdm5QbZ',
            transaction_type: 'special',
            unofficial_currency_code: null
        },
        {
            account_id: 'r3qp4zVLnmCJ6mBBALp5Ivbnmv98gjilPXG8R',
            account_owner: null,
            amount: 12,
            category: [Array],
            category_id: '13005000',
            date: '2019-03-19',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'McDonald\'s',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'KER1rqQeDltwoWRRAZ8dC9y3nz8Ag8fVZj5wa',
            transaction_type: 'place',
            unofficial_currency_code: null
        },
        {
            account_id: 'r3qp4zVLnmCJ6mBBALp5Ivbnmv98gjilPXG8R',
            account_owner: null,
            amount: 4.33,
            category: [Array],
            category_id: '13005043',
            date: '2019-03-19',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'Starbucks',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'r3qp4zVLnmCJ6mBBALp5IvbnDMe5KeulPXGKg',
            transaction_type: 'place',
            unofficial_currency_code: null
        },
        {
            account_id: 'r3qp4zVLnmCJ6mBBALp5Ivbnmv98gjilPXG8R',
            account_owner: null,
            amount: 89.4,
            category: [Array],
            category_id: '13005000',
            date: '2019-03-18',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'SparkFun',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'z7JkEPq4XDcl5L99mr1Ac1exym5W45ho7KePL',
            transaction_type: 'place',
            unofficial_currency_code: null
        },
        {
            account_id: '7BP6WZAJD9SyndMM6jaeuQ9bAQD5xWiglawDa',
            account_owner: null,
            amount: -4.22,
            category: [Array],
            category_id: '13005000',
            date: '2019-03-17',
            iso_currency_code: 'USD',
            location: [Object],
            name: 'INTRST PYMNT',
            payment_meta: [Object],
            pending: false,
            pending_transaction_id: null,
            transaction_id: 'xPxAZ4VdnQIW7yddBK9gi1MBp53g93hn7ZQlK',
            transaction_type: 'place',
            unofficial_currency_code: null
        }
    ],
    status_code: 200
};

export default fakeResponse;
