/*
 * getCombinedStyles combines styles
 *   from the inner style and className generated by withStyles
 *   from the outer style and className passed in by a higher component
 *
 * Use:
 *   const combinedStyles = getCombinedStyles(props, styles.a, styles.b, ...);
 *   <SomeComponent {...combinedStyles} />
 */
const getCombinedStyles = ({css, className, style}, ...innerStyleList) => {
  // eslint-disable-next-line react-with-styles/only-spread-css
  const {className: innerClassName, style: innerStyle} = css(innerStyleList);
  const combinedClassName = `${className} ${innerClassName}`;
  const combinedStyle = style._definition // eslint-disable-line no-underscore-dangle
    ? {...innerStyle, ...style._definition} // eslint-disable-line no-underscore-dangle
    : {...innerStyle, ...style};

  return {
    className: combinedClassName,
    style: combinedStyle,
  };
};

export default getCombinedStyles;
